import {resume} from './src/content.js';
import {writeFileSync,copyFileSync} from 'node:fs';
copyFileSync('src/placeholderimages.png','dist/assets/gallery/placeholderimages.png');
const esc=s=>String(s??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const title=s=>s.split('<br>').map(esc).join('<br>');
const action=a=>a.href?.startsWith('#project')?`<button class="resume-link" type="button" data-open-project="${esc(a.href==='#projects'?'':a.href.slice(1))}">${esc(a.label)}</button>`:a.href?`<a class="resume-link" href="${esc(a.href)}">${esc(a.label)}</a>`:`<span class="unlinked-action">${esc(a.label)}</span>`;
function block(b){
  switch(b.type){
    case 'contactRow':{
      const icons={phone:'<path d="M7 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-3l-5-2-2 2a14 14 0 0 1-7-7l2-2-2-5Z"/>',email:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 6 9 7 9-7"/>',github:'<path d="M9 19c-4 1-4-2-6-2m12 5v-4a3.5 3.5 0 0 0-1-2.5c3.3-.4 6.7-1.6 6.7-7A5.5 5.5 0 0 0 19 4.7 5 5 0 0 0 18.9 1S17.6.6 15 2.4a13.4 13.4 0 0 0-6 0C6.4.6 5.1 1 5.1 1A5 5 0 0 0 5 4.7a5.5 5.5 0 0 0-1.7 3.8c0 5.4 3.4 6.6 6.7 7A3.5 3.5 0 0 0 9 18v4"/>'};
      return `<div class="intro-contacts" aria-label="Contact details">${b.links.map(a=>`<a href="${esc(a.href)}"${a.external?' target="_blank" rel="noopener noreferrer"':''}><svg viewBox="0 0 24 24" aria-hidden="true" focusable="false" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round">${icons[a.icon]}</svg><span>${esc(a.label)}</span></a>`).join('')}</div>`;
    }
    case 'direction':return `<div class="direction"><span>${esc(b.label)}</span><p>${esc(b.text)}</p></div>`;
    case 'paragraph':return `<p class="${b.lead?'lead':'body-copy'}">${esc(b.text)}</p>`;
    case 'heading':return `<h3 class="subheading">${esc(b.text)}</h3>`;
    case 'certification':return `<div class="certification"><p>${esc(b.text)}</p>${b.institution?`<p class="metadata">${esc(b.institution)}</p>`:''}<p class="metadata">${esc(b.meta)}</p>${b.result?`<p class="metadata">${esc(b.result)}</p>`:''}</div>`;
    case 'link':return action(b);
    case 'caseStudy':return `<article class="case-study" id="${esc(b.id)}"><p class="metadata">${esc(b.meta)}</p><h3 class="subheading">${esc(b.title)}</h3><p class="body-copy">${esc(b.summary)}</p><h4>The challenge</h4><p class="body-copy">${esc(b.challenge)}</p><h4>My contribution</h4><p class="body-copy">${esc(b.contribution)}</p><p class="metadata">${esc(b.tools)}</p>${b.links.length?`<h4>Live websites</h4><ul class="live-links">${b.links.map(a=>`<li><a href="${esc(a.href)}" target="_blank" rel="noopener noreferrer">${esc(a.label)}</a></li>`).join('')}</ul>`:''}</article>`;
    case 'entry':return `<article class="entry"><p class="metadata">${esc(b.meta)}</p><h3>${esc(b.title)}</h3><p>${esc(b.text)}</p>${b.action?action(b.action):''}</article>`;
    default:throw new Error(`Unknown content block: ${b.type}`);
  }
}
const projects=resume.sections.find(s=>s.id==='projects').blocks;
const sections=resume.sections.filter(s=>s.id!=='projects').map((s,i)=>`<section class="resume-section ${i===0?'intro':''}" id="${s.id}" aria-labelledby="heading-${i}"><p class="eyebrow">${esc(s.label)}</p><${i===0?'h1':'h2'} class="section-title" id="heading-${i}">${title(s.title)}</${i===0?'h1':'h2'}>${s.blocks.map(block).join('')}</section>`).join('');
const gallery=p=>Array.from({length:3},(_,i)=>{const img=p.images?.[i]||{src:'./assets/gallery/placeholderimages.png',alt:'Project screenshot placeholder'};return `<figure class="gallery-print" data-photo="${i}"><img src="${esc(img.src)}" alt="${esc(img.alt)}"></figure>`;}).join('');
const portfolio=`<main id="portfolio" hidden aria-labelledby="portfolio-heading"><div class="portfolio-back"><button id="back-profile" type="button">← Back</button></div><div class="portfolio-toolbar"><div class="project-navigation"><button id="previous-project" type="button" aria-label="Previous project">←</button><label class="sr-only" for="project-choice">Choose project</label><select id="project-choice">${projects.map((p,i)=>`<option value="${i}">${esc(p.title)}</option>`).join('')}</select><button id="next-project" type="button" aria-label="Next project">→</button></div></div><div class="portfolio-layout"><section class="portfolio-paper" id="project-details" aria-labelledby="portfolio-heading"><p class="eyebrow">Selected projects</p><h1 id="portfolio-heading" class="sr-only" tabindex="-1">Project portfolio</h1>${projects.map((p,i)=>`<div class="project-document" data-project="${esc(p.id)}" ${i?'hidden':''}>${block(p)}</div>`).join('')}</section><aside class="gallery-column" aria-label="Project gallery"><div class="photo-stack"><div class="portfolio-paper gallery-paper" id="gallery-paper">${projects.map((p,i)=>`<div class="project-gallery" data-gallery="${esc(p.id)}" ${i?'hidden':''}>${gallery(p)}</div>`).join('')}</div></div></aside></div><p id="portfolio-status" class="sr-only" aria-live="polite"></p></main>`;
const html=`<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#241c17"><meta name="description" content="${esc(resume.name)} — ${esc(resume.direction)}."><title>${esc(resume.name)} — Résumé</title><link rel="icon" href="./favicon.svg"><link rel="stylesheet" href="./style.css"></head><body><a class="skip" href="#heading-0">Skip to résumé</a><header class="site-header"><a class="wordmark" href="#heading-0" aria-label="${esc(resume.name)}, beginning of résumé">lt<span>.</span></a><a href="?view=simple" id="view-toggle">Read simple version</a></header><main id="resume"><div class="held-assembly"><article class="paper" aria-label="Complete résumé"><div class="paper-meta"><span>${esc(resume.name)}</span><span>RÉSUMÉ</span></div>${sections}</article></div></main><div class="scroll-hint" aria-hidden="true">SCROLL TO READ <span>↓</span></div><script type="module" src="./app.js"></script></body></html>`;
writeFileSync('dist/index.html',html.replace('<div class="scroll-hint"',`${portfolio}<noscript><style>#portfolio[hidden],.project-document[hidden]{display:block!important}.portfolio-toolbar,.gallery-column,[data-open-project]{display:none!important}</style></noscript><div class="scroll-hint"`));
writeFileSync('dist/favicon.svg','<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="#282019"/><text x="13" y="44" font-family="Georgia" font-size="42" fill="#f1e9d9">lt.</text></svg>');
console.log(`Built the continuous résumé and a dedicated portfolio containing ${projects.length} projects.`);


