const {chromium}=require('C:/Users/HP/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch({headless:true,channel:'msedge'}),p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:4185');await p.waitForSelector('.scene-3d');
await p.evaluate(()=>{window.samples=[];window.sampleMotion=true;async function record(){const d=(await import('./scene.js')).getSceneDiagnostics();samples.push({c:d.coordination,pose:d.pose,hands:d.hands});if(window.sampleMotion)requestAnimationFrame(record);}record();});
await p.evaluate(()=>scrollTo({top:500,behavior:'instant'}));
const captured=new Set();for(let n=0;n<85;n++){await p.waitForTimeout(45);const state=await p.evaluate(()=>samples.at(-1));for(const h of state.c.hands){if(h.phase!=='grip'&&!captured.has(h.phase)){captured.add(h.phase);await p.screenshot({path:`verification/handover-${h.phase}.png`});}}}
await p.waitForFunction(async()=>!(await import('./scene.js')).getSceneDiagnostics().coordination.active,{},{timeout:8000});await p.screenshot({path:'verification/handover-settled.png'});
for(const top of [650,820,1000,1100,980,800,650,500]){await p.evaluate(y=>scrollTo({top:y,behavior:'instant'}),top);await p.waitForTimeout(70);}
await p.waitForFunction(async()=>{const d=(await import('./scene.js')).getSceneDiagnostics();if(d.coordination.active||d.coordination.pending||scrollY!==500){window.settledSince=0;return false;}window.settledSince ||= performance.now();return performance.now()-window.settledSince>350;},{},{timeout:12000});
await p.waitForTimeout(3500);
const samples=await p.evaluate(async()=>{sampleMotion=false;const d=(await import('./scene.js')).getSceneDiagnostics();window.samples.push({c:d.coordination,pose:d.pose,hands:d.hands});return window.samples;});assert.deepEqual(errors,[]);for(const s of samples){assert(s.c.hands.filter(h=>h.phase!=='grip').length<=1);for(const h of s.c.hands.filter(h=>h.phase==='grip'))assert(Math.abs(h.y-(s.pose.top+h.anchor))<.01);}
const observed=new Set(samples.flatMap(s=>s.c.hands.map(h=>h.phase)));for(const phase of ['release','depart','travel','approach','regrip'])assert(observed.has(phase),phase);for(const side of ['left','right'])assert(samples.some(s=>s.c.active===side));assert(samples.some(s=>s.hands.some(h=>h.opening>.95)));
for(const h of samples.at(-1).hands)assert.equal(h.opening,0);fs.writeFileSync('verification/handover.json',JSON.stringify({phases:[...observed],frames:samples.length,errors},null,2));console.log('PASS: full source phase sequence, both hands alternate, one support always attached, visible opening, reverse scrolling, completion after scrolling stops.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});

